import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Output, Input
import glob
from numpy.lib.utils import source
import pandas as pd
import numpy as np
import plotly.express as px
import geopandas as gpd
import plotly.graph_objects as go

#Для pickerов
afb_codes = ['LTAG',
'KLTS',
 'PGUA',
 'OAIX',
 'KVBG',
 'KDYS',
 'KDMA',
 'RODN',
 'BIKF',
 'RKJK',
 'EGUL',
 'KLFI',
 'UCFM',
 'EGUN',
 'KLSV',
 'KOFF',
 'ETAR',
 'KROW',
 'BGTL',
 'KSZL',
 'EGVA',
 'KEDW',
 'PAED',
 'KADW',
 'KVOK',
 'LIPA',
 'KRIV',
 'KSUU',
 'KWHP',
 'EETU',
 'EETN',
 'EEPU',
 'EEKA',
 'EVRA',
 'EVVA',
 'EVLA',
 'EYVI',
 'EYKA',
 'EYSA',
 'EYPA',
 'EPGD',
 'EPSC',
 'EPBY',
 'EPPO',
 'EPMO',
 'EPWA',
 'EPLL',
 'EPLB',
 'EPWR',
 'EPKT',
 'EPKK',
 'EPRZ',
 'UKKK',
 'UKLR',
 'UKKM',
 'UKWW',
 'LTBJ',
 'LTAF',
 'UGTB',
 'UKBB',
 'LKPD',
 'OAKB',
 'LFSB',
 'EHWO',
 'OMAM',
 'OMDM',
 'KDOV',
 'KSKF',
 'OABT',
 'OACC',
 'OAFR',
 'OAHR',
 'OAKN',
 'OAMS',
 'OATN',
 'OAZJ',
 'LZIB',
 'LZKZ',
 'LZPP',
 'LZTT',
 'LZSL',
 'LZZI',
 'LJLJ',
 'LJMB',
 'LRAR',
 'LRBC',
 'LRBM',
 'LROV',
 'LROP',
 'LRBS',
 'LRCL',
 'LRCK',
 'LRCV',
 'LRIA',
 'LROD',
 'LRSM',
 'LRSB',
 'LRSV',
 'LRTM',
 'LRTR',
 'UTDD',
 'UTDL',
 'UTDK',
 'UTDT',
 'UKLN',
 'UKDD',
 'UKCC',
 'UKLI',
 'UKHH',
 'UKOH',
 'UKDR',
 'UKLL',
 'UKON',
 'UKOO',
 'UKHP',
 'UKFF',
 'UKLU',
 'UKDE',
 'UKKV',
 'LTCP',
 'LTCO',
 'LTAC',
 'LTDA',
 'LTAI',
 'LTCJ',
 'LTCU',
 'LTFE',
 'LTBR',
 'LTBH',
 'LTAY',
 'LTBS',
 'LTCC',
 'LTFD',
 'LTCA',
 'LTCD',
 'LTCE',
 'LTBY',
 'LTAJ',
 'LTFG',
 'LTCT',
 'LTFC',
 'LTFM',
 'LTFJ',
 'LTBA',
 'LTBQ',
 'LTCN',
 'LTCF',
 'LTAL',
 'LTAU',
 'LTAN',
 'LTBZ',
 'LTAT',
 'LTCR',
 'LTAP',
 'LTCK',
 'LTAZ',
 'LTCB',
 'LTFH',
 'LTCS',
 'LTCL',
 'LTCM',
 'LTCV',
 'LTAR',
 'LTBU',
 'LTAW',
 'LTCG',
 'LCEN',
 'LTBO',
 'LTCI',
 'LTCW',
 'LTAS',
 'UTAA',
 'UTAT',
 'UTAE',
 'UTAM',
 'UTAV',
 'UTAK',
 'ESTA',
 'ESNX',
 'ESSD',
 'ESSU',
 'ESNG',
 'ESSK',
 'ESGG',
 'ESGP',
 'ESOH',
 'ESMT',
 'ESUT',
 'ESSF',
 'ESGJ',
 'ESMQ',
 'ESKK',
 'ESOK',
 'ESNQ',
 'ESNK',
 'ESMK',
 'ESGL',
 'ESSL',
 'ESTL',
 'ESPA',
 'ESNL',
 'ESMS',
 'ESKM',
 'ESSP',
 'ESSN',
 'ESOE',
 'ESNO',
 'ESNZ',
 'ESUP',
 'ESDF',
 'ESKS',
 'ESNS',
 'ESGR',
 'ESKN',
 'ESSB',
 'ESOW',
 'ESSA',
 'ESNN',
 'ESND',
 'ESST',
 'ESGT',
 'ESNU',
 'ESSW',
 'ESMX',
 'ESNV',
 'ESSV',
 'LSZB',
 'LSZC',
 'LSGE',
 'LSGG',
 'LSZG',
 'LSGC',
 'LSGL',
 'LSZL',
 'LSZA',
 'LSPM',
 'LSGS',
 'LSZR',
 'LSZS',
 'LSZH',
 'OSKL',
 'OSAP',
 'OSDI',
 'OSLK',
 'EPBP',
 'EPRU',
 'EPKO',
 'EPML',
 'EPSY',
 'EPRA',
 'EPBC',
 'EPZG',
 'GLRB',
 'HLZN',
 'HLLQ',
 'HLLB',
 'HLGT',
 'HLMS',
 'HLLS',
 'HLGN',
 'HLLM',
 'HLLT',
 'HLZW',
 'EEKE',
 'LHBP',
 'LHDC',
 'LHFM',
 'LHPR',
 'LHNY',
 'LHPP',
 'LHSM',
 'LHUD',
 'LAKU',
 'LATI',
 'DAUA',
 'DAAG',
 'DABB',
 'DABT',
 'DAAE',
 'DAUB',
 'DAOI',
 'DABC',
 'DAAJ',
 'DAUO',
 'DAUG',
 'DAUH',
 'DAAP',
 'DAAV',
 'DAUL',
 'DAOO',
 'DAUU',
 'DAAS',
 'DAAT',
 'DAOF',
 'DAON',
 'AT07',
 'SCRM',
 'AT16',
 'AT17',
 'AT99',
 'AT22',
 'ENOE',
 'LOWG',
 'LOIH',
 'LOWI',
 'LOWK',
 'LOWL',
 'LOWS',
 'LOWW',
 'LOAN',
 'UBBB',
 'UBBF',
 'UBBL',
 'UBBN',
 'UBBQ',
 'UMBB',
 'UMGG',
 'UMMG',
 'UMMS',
 'UMOO',
 'UMII',
 'EBAW',
 'EBBR',
 'EBCI',
 'EBKT',
 'EBLG',
 'EBOS',
 'SLCH',
 'SLCO',
 'SLCB',
 'SLGY',
 'SLLP',
 'SLOR',
 'SLRI',
 'SLRQ',
 'SLET',
 'SLVR',
 'SLAL',
 'SLTJ',
 'SLTR',
 'SLUY',
 'LBBG',
 'LBPD',
 'LBSF',
 'LBWN']
#Для pickerов
afb_names = ['Incirlik',
 'Altus AFB',
 'Andersen AFB',
 'Logistics Support Area Anaconda',
 'Vandenberg AFB',
 'Dyess AFB',
 'Davis Monthan AFB',
 'Kadena AB',
 'Keflavik International Airport',
 'Gunsan Airport',
 'RAF Lakenheath',
 'Langley AFB',
 'Bishkek Manas International Airport',
 'RAF Mildenhall',
 'Nellis AFB',
 'Offutt AFB',
 'Ramstein Air Base',
 'Roswell International Air Center Airport',
 'Pituffik Airport',
 'Whiteman AFB',
 'Fairford',
 'Edwards AFB',
 'Anchorage Elmendorf Air Force Base',
 'Andrews Air Force Base',
 'Volk Field',
 'Aviano',
 'Riverside March Air Reserve Base',
 'Fairfield Travis Air Force Base',
 'Los Angeles Whiteman Airport',
 'Tartu Airport',
 'Tallinn Lennart Meri Airport ',
 'Parnu Airport',
 'Kardla Airport',
 'Riga International Airport',
 'Ventspils International Airport',
 'Liepaja Airport',
 'Vilnius International Airport',
 'Kaunas Airport',
 'Siauliai International Airport',
 'Palanga International Airport',
 'Gdansk Lech Walesa Airport',
 'Szczecin Goleniow Airport',
 'Bydgoszcz Ignacy Jan Paderewski Airport',
 'Poznan Lawica Airport',
 'Warsaw Modlin Airport',
 'Warsaw Chopin Airport',
 'Lodz Wladyslaw Reymont Airport',
 'Lublin Airport',
 'Wroclaw Copernicus Airport',
 'Katowice International Airport',
 'Krakow John Paul II International Airport',
 'Rzeszow Jasionka Airport',
 'Kyiv Zhuliany Airport',
 'Rivne International Airport',
 'Kyiv Hostomel Airport',
 'Vinnytsia Havryshivka International Airport',
 'Izmir Adnan Menderes International Airport',
 'Adana Sakirpasa Airport',
 'Tbilisi International Airport',
 'Kyiv Boryspil International Airport',
 'Pardubice Airport',
 'Kabul International Airport',
 'Basel Mulhouse-Freiburg EuroAirport',
 'Bergen op Zoom Woensdrecht Air Base Airport',
 'Abu Dhabi Al Dhafra Air Base',
 'Dubai Al Minhad Air Base',
 'Dover Air Force Base',
 'San Antonio Lackland Air Force Base',
 'Bost Airport',
 'Chaghcharan Airport',
 'Farah Airport',
 'Herat International Airport',
 'Kandahar Airport',
 'Mazar-I-Sharif International Airport',
 'Tarinkot Airport',
 'Zaranj Airport',
 'Bratislava M. R. Stefanik Airport',
 'Kosice International Airport',
 'Piestany Airport',
 'Poprad Tatry Airport',
 'Sliac Airport',
 'Zilina Airport',
 'Ljubljana Joze Pucnik Airport',
 'Maribor Airport',
 'Arad International Airport',
 'Bacau International Airport',
 'Baia Mare Airport',
 'Brasov Airport',
 'Bucharest Henri Coanda International Airport',
 'Bucharest Aurel Vlaicu Airport',
 'Cluj-Napoca International Airport',
 'Constanta International Airport',
 'Craiova International Airport',
 'Iasi International Airport',
 'Oradea International Airport',
 'Satu Mare International Airport',
 'Sibiu International Airport',
 'Suceava International Airport',
 'Targu Mures International Airport',
 'Timisoara Traian Vuia International Airport',
 'Dushanbe International Airport',
 'Khudzhand Khujand Airport',
 'Kulob Airport',
 'Kurgan Tyube Qurghonteppa International Airport',
 'Chernivtsi International Airport',
 'Dnipro Dnipropetrovsk International Airport',
 'Donetsk Sergey Prokofiev International Airport',
 'Ivano-Frankivsk International Airport',
 'Kharkiv International Airport',
 'Kherson International Airport',
 'Kryvyi Rih International Airport',
 'Lviv Danylo Halytskyi International Airport',
 'Mykolaiv International Airport',
 'Odesa International Airport',
 'Poltava International  Airport',
 'Simferopol International Airport',
 'Uzhhorod International Airport',
 'Zaporizhzhia International Airport',
 'Zhytomyr Airport',
 'Adiyaman Airport',
 'Agri Airport',
 'Ankara Esenboga International Airport',
 'Antakya Hatay Airport',
 'Antalya Airport',
 'Batman Airport',
 'Bingol Airport',
 'Bodrum Milas Airport',
 'Bursa Yenisehir Airport',
 'Canakkale Airport',
 'Denizli Cardak Airport',
 'Dalaman Airport',
 'Diyarbakir Airport',
 'Edremit Balikesir Koca Seyit Airport',
 'Elazig Airport',
 'Erzincan Airport',
 'Erzurum Airport',
 'Eskisehir Airport',
 'Gaziantep Oguzeli Airport',
 'Gazipasa Airport',
 'Igdir Airport',
 'Isparta Suleyman Demirel Airport',
 'Istanbul Airport',
 'Istanbul Sabiha Gokcen International Airport',
 'Istanbul Ataturk Airport',
 'Izmit Topel Airport',
 'Kahramanmaras Airport',
 'Kars Harakani Airport',
 'Kastamonu Airport',
 'Kayseri Erkilet International Airport',
 'Konya Airport',
 'Kutahya Zafer Airport',
 'Malatya Erhac Airport',
 'Mardin Airport',
 'Merzifon Airport',
 'Mus Airport',
 'Nevsehir Kapadokya Airport',
 'Ordu Giresun Airport',
 'Samsun Carsamba Airport',
 'Sanliurfa GAP Airport',
 'Siirt Airport',
 'Sinop Airport',
 'Sirnak Airport',
 'Sivas Nuri Demirag Airport',
 'Tekirdag Corlu Airport',
 'Tokat Airport',
 'Trabzon Airport',
 'Ercan International Airport',
 'Usak Airport',
 'Van Airport',
 'Yuksekova Hakkari Airport',
 'Zonguldak Airport',
 'Ashgabat International Airport',
 'Dasoguz Airport',
 'Kerki International Airport',
 'Mary International Airport',
 'Turkmenabat International Airport',
 'Turkmenbashi International Airport',
 'Angelholm Helsingborg Airport',
 'Arvidsjaur Airport',
 'Borlange Dala Airport',
 'Eskilstuna Airport',
 'Gallivare Lapland Airport',
 'Gavle Airport',
 'Gothenburg Landvetter Airport',
 'Gothenburg City Airport',
 'Hagfors Airport',
 'Halmstad Airport',
 'Hemavan Airport',
 'Hultsfred Airport',
 'Jonkoping Airport',
 'Kalmar Airport',
 'Karlskoga Airport',
 'Karlstad Airport',
 'Kiruna Airport',
 'Kramfors Hoga Kusten Airport',
 'Kristianstad Osterlen Airport',
 'Lidkoping Hovby Airport',
 'Linkoping City Airport',
 'Ljungbyhed Airport',
 'Lulea Airport',
 'Lycksele Airport',
 'Malmo Airport',
 'Mora Siljan Airport',
 'Norrkoping Airport',
 'Norrtalje Mellingeholms Airport',
 'Orebro Airport',
 'Ornskoldsvik Airport',
 'Ostersund Are Airport',
 'Pajala Airport',
 'Ronneby Airport',
 'Salen Scandinavian Mountains Airport',
 'Skelleftea Airport',
 'Skovde Airport',
 'Stockholm Skavsta Airport',
 'Stockholm Bromma Airport',
 'Stockholm Vasteras Hasslo Airport',
 'Stockholm Arlanda Airport',
 'Sundsvall Timra Airport',
 'Sveg Harjedalen Airport',
 'Torsby Airport',
 'Trollhattan Vanersborg Airport',
 'Umea Airport',
 'Vastervik Airport',
 'Vaxjo Smaland Airport',
 'Vilhelmina Airport',
 'Visby Airport',
 'Bern Airport',
 'Buochs Airport',
 'Fribourg Ecuvillens Airport',
 'Geneva International Airport',
 'Grenchen Airport',
 'La Chaux-de-Fonds Les Eplatures Airport',
 'Lausanne Airport',
 'Locarno Airport',
 'Lugano Airport',
 'Quinto Ambri Airport',
 'Sion Airport',
 'St. Gallen Altenrhein Airport',
 'St. Moritz Samedan Airport',
 'Zurich Airport',
 'Al-Qamishli Airport',
 'Aleppo International Airport',
 'Damascus International Airport',
 'Latakia Bassel al Assad International Airport',
 'Biala Podlaska Airport',
 'Czestochowa Rudniki Airport',
 'Koszalin Zegrze Pomorskie Airport',
 'Mielec Airport',
 'Olsztyn Mazury Airport',
 'Radom Airport',
 'Warsaw Babice Airport',
 'Zielona Gora Babimost Airport',
 'Monrovia Roberts International Airport',
 'Alzintan Airport',
 'Beida Al Abraq International Airport',
 'Benghazi Benina International Airport',
 'Ghat Airport',
 'Misrata International Airport',
 'Sabha Airport',
 'Tobruk Airport',
 'Tripoli Mitiga International Airport',
 'Tripoli International Airport',
 'Zwara Airport',
 'Kuressaare Airport',
 'Budapest Ferenc Liszt International Airport',
 'Debrecen International Airport',
 'Fertoszentmiklos Meidl Airport',
 'Gyor Per Airport',
 'Nyiregyhaza Airport',
 'Pecs Pogany Airport',
 'Heviz Balaton Airport',
 'Szeged Airport',
 'Kukes International Airport',
 'Tirana International Airport',
 'Adrar Airport',
 'Algiers Houari Boumediene Airport',
 'Annaba Rabah Bitat Airport',
 'Batna International Airport',
 'Bejaia Soummam Airport',
 'Biskra Airport',
 'Chlef International Airport',
 'Constantine Mohamed Boudiaf International Airport',
 'Djanet Inedbirene Airport',
 'El Oued Guemar Airport',
 'Ghardaia Noumerate Airport',
 'Hassi Messaoud Oued Irara Airport',
 'Illizi Takhamalt Airport',
 'Jijel Ferhat Abbas Airport',
 'Laghouat Airport',
 'Oran Es Senia Airport',
 'Ouargla Ain Beida Airport',
 'Setif Ain Arnat Airport',
 'Tamanrasset Aguenar Airport',
 'Tindouf Airport',
 'Tlemcen Zenata Airport',
 'Davis Plateau Skiway',
 'King George Island Teniente R. Marsh Airport',
 'Neumayer III Skiway',
 'Novo Runway',
 'Princess Elisabeth Skiway',
 'SANAE IV Skiway',
 'Troll Airfield',
 'Graz Airport',
 'Hohenems Dornbirn Airport',
 'Innsbruck Kranebitten Airport',
 'Klagenfurt Airport',
 'Linz Airport',
 'Salzburg Airport',
 'Vienna International Airport',
 'Wiener Neustadt East Airport',
 'Baku Heydar Aliyev International Airport',
 'Fuzuli International Airport',
 'Lankaran International Airport',
 'Nakhchivan International Airport',
 'Qabala International Airport',
 'Brest Airport',
 'Gomel Airport',
 'Grodno Hrodna Airport',
 'Minsk International Airport',
 'Mogilev Airport',
 'Vitebsk Vostochny Airport',
 'Antwerp International Airport',
 'Brussels Airport',
 'Brussels South Charleroi Airport',
 'Kortrijk Wevelgem International Airport',
 'Liege Airport',
 'Ostend Bruges International Airport',
 'Chimore Airport',
 'Cobija Capitan Anibal Arab Airport',
 'Cochabamba Jorge Wilstermann International Airport',
 'Guayaramerin Airport',
 'La Paz El Alto International Airport',
 'Oruro Juan Mendoza Airport',
 'Riberalta Airport',
 'Rurrenabaque Airport',
 'Santa Cruz El Trompillo Airport',
 'Santa Cruz Viru Viru International Airport',
 'Sucre Alcantari International Airport',
 'Tarija Airport',
 'Trinidad Teniente Jorge Henrich Arauz Airport',
 'Uyuni Joya Andina Airport',
 'Burgas Airport',
 'Plovdiv Airport',
 'Sofia Airport',
 'Varna Airport']
#Словарь транспортных судов
mtList = {'Lockheed C-5 Galaxy' : 'Military Transport',
          'Lockheed C-5A Galaxy' : 'Military Transport',
          'Lockheed Martin C-5A Galaxy' : 'Military Transport',
          'C-5A':'Military Transport',
          'C-5B':'Military Transport',
          'C-5C':'Military Transport',
          'C-5M':'Military Transport',
          'C-5':'Military Transport',
          'Boeing C-17A Globemaster III':'Military Transport',
          'Boeing C-17 Globemaster III':'Military Transport',
          'C-17': 'Military Transport',
          'C-17A':'Military Transport',
          'Lockheed C-130 Hercules':'Military Transport',
          'Lockheed Martin C-130 Hercules':'Military Transport',
          'C-130':'Military Transport',
          'C-130H':'Military Transport',
          'С-130J':'Military Transport',
          'Beechcraft C-12 Huron':'Military Transport',
          'С-12С':'Military Transport',
          'C-12D':'Military Transport',
          'C-12F':'Military Transport',
          'C-12J':'Military Transport',
          'UC-12F':'Military Transport',
          'UC-12M':'Military Transport',
          'UC-12W':'Military Transport',
          'C-20':'Military Transport',
          'C-21A':'Military Transport',
          'С 21А':'Military Transport',
          'C-26 Metroliner':'Military Transport',
          'C-26B':'Military Transport',
          'RC-26':'Military Transport',
          'Boeing C-32':'Military Transport',
          'C-32A':'Military Transport',
          'C-32B':'Military Transport',
          'C-37A':'Military Transport',
          'C-38A':'Military Transport',
          'C-40':'Military Transport',
          'C-40B':'Military Transport',
          'C-40C':'Military Transport',
          'C-144':'Military Transport',
          'C-146A Wolfhound':'Military Transport',
          'U-28A':'Military Transport',
          'Antonov An-225 Mriya':'Military Transport',
          'Antonov An-124-100-150':'Military Transport' }


import os

path = ('/Users/mac/Desktop/studying/Dash/datasets/flight_data')
files = os.listdir(path)
combined = pd.DataFrame()
for file in files:
    if file.endswith('.csv'):
        data = pd.read_csv(path+'/'+file)
        combined = pd.concat([combined, data])
#Объединение всех файлов csv из указанной папки
files = glob.glob('/Users/mac/Desktop/Data/flight_data_2')
#Объединяем
# combined = pd.DataFrame()
# for i in files:
#     data = pd.read_csv(i)
#     combined = pd.concat([combined, data])

#For pickers
pickData = pd.read_csv('/Users/mac/Desktop/studying/Dash/afbForPickers.csv')

#Таблица для первого блока
diagram_data = combined
diagram_data = diagram_data.groupby(['today','afb',]).agg({'text':'size'}).reset_index(level=['today','afb'])
diagram_data["today"] = pd.to_datetime(diagram_data["today"], format="%Y-%m-%d")

#Мердж
afb_details_data = pd.read_csv('/Users/mac/Desktop/studying/Dash/afbDetails.csv')
afb_details_data = afb_details_data.rename(columns={'code':'afb'})
merged_data = diagram_data.merge(afb_details_data, on='afb')

#Функция определения типа самолета
pie_data = combined
def check_type(data):
    data['type'] = diagram_data['text'].map(mtList)
    data['type'].fillna('Civil', inplace=True)
    return data

#Таблица для пай-чарта
pie_data = check_type(pie_data)

#Подготовка данных для пай-чарта
civils = 0
military = 0
labels = ['Military Transport Aircarft','Civil Aircraft']
values = [military, civils]
#Построение пай чарта
pie_fig = go.Figure(data=[go.Pie(labels=labels, values=values)])

#Таблица для скаттер-гео чарта
scatter_data = merged_data
scatter_data["today"] = pd.to_datetime(scatter_data["today"], format="%Y-%m-%d")
scatter_data['out'] = scatter_data['name'] + ', ' + scatter_data['city'] + ', ' + scatter_data['country'] ######Надо сравнить со списком
scatter_data = scatter_data.rename(columns={'text':'activity'})

#Построение скаттер-гео чарта
scatter_fig = px.scatter_mapbox(scatter_data,
        lon = scatter_data['longitude'],
        lat = scatter_data['latitude'],
        text = scatter_data['activity'],
        color = scatter_data['country'],
        size = scatter_data['activity'],
        hover_name = scatter_data['out'],
        hover_data = {'country':False,
                     'latitude':False,
                     'longitude':False,
                     'out':False},
        color_discrete_sequence=["fuchsia"],
        zoom=3,
        height=300,
        mapbox_style='stamen- terrain'
        )


#Самая загруженная авиабаза
most_busy = scatter_data[scatter_data['activity'] == scatter_data.activity.max()]
